version: "3.9"

services:
  # Base de Datos NoSQL Persistente (MongoDB)
  mongodb:
    image: mongo:7.0
    container_name: hbp_mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - hbp_network
    restart: always

  # Almacenamiento en Caché de Rápido Acceso (Redis)
  redis:
    image: redis:7-alpine
    container_name: hbp_redis
    ports:
      - "6379:6379"
    networks:
      - hbp_network
    restart: always

  # Nodo Master (Orquestador API REST, WebSockets, Caching y Coordinador RPC)
  master:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        APP_DIR: master
    container_name: hbp_master
    ports:
      - "8080:8080"
    environment:
      - MONGO_URI=mongodb://mongodb:27017
      - REDIS_URI=redis://redis:6379
    command: ["-api", "-workers=worker1:8081,worker2:8081", "-port=:8080"]
    depends_on:
      - mongodb
      - redis
      - worker1
      - worker2
    networks:
      - hbp_network
    restart: always

  # Nodo Worker 1 (Cálculo Concurrente ML)
  worker1:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        APP_DIR: worker_node
    container_name: hbp_worker1
    command: ["-addr=:8081", "-pprof=:6061", "-id=1"]
    networks:
      - hbp_network
    restart: always

  # Nodo Worker 2 (Cálculo Concurrente ML)
  worker2:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        APP_DIR: worker_node
    container_name: hbp_worker2
    command: ["-addr=:8081", "-pprof=:6061", "-id=2"]
    networks:
      - hbp_network
    restart: always

  # Frontend Nginx (Servidor Web Estático para SPA)
  nginx:
    image: nginx:alpine
    container_name: hbp_frontend
    ports:
      - "8082:80"
    volumes:
      - ./frontend:/usr/share/nginx/html:ro
    networks:
      - hbp_network
    restart: always

volumes:
  mongodb_data:

networks:
  hbp_network:
    name: hbp_network
    driver: bridge
