version: "3.9"

services:
  # Nodo Master (Orquestador REST API)
  master:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        APP_DIR: master
    container_name: hbp_master
    ports:
      - "8080:8080"
    command: ["-api", "-workers=worker1:8081,worker2:8081", "-port=:8080"]
    depends_on:
      - worker1
      - worker2
    networks:
      - hbp_network
    restart: always

  # Nodo Worker 1
  worker1:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        APP_DIR: worker_node
    container_name: hbp_worker1
    command: ["-addr=:8081", "-pprof=:6061", "-id=1"]
    networks:
      - hbp_network
    restart: always

  # Nodo Worker 2
  worker2:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        APP_DIR: worker_node
    container_name: hbp_worker2
    command: ["-addr=:8081", "-pprof=:6061", "-id=2"]
    networks:
      - hbp_network
    restart: always

  # Frontend Nginx (Servidor Web Estático)
  nginx:
    image: nginx:alpine
    container_name: hbp_frontend
    ports:
      - "80:80"
    volumes:
      - ./frontend:/usr/share/nginx/html:ro
    networks:
      - hbp_network
    restart: always

networks:
  hbp_network:
    name: hbp_network
    driver: bridge
